import io
import os
import zipfile

import numpy as np
import pandas as pd
from shiny import App, reactive, render, ui

from maxent_solver import (
    prepare_dataframe, optimize_weights, predict_probabilities,
    compute_errors, format_output, has_hidden_structure,
)

HERE = os.path.dirname(os.path.abspath(__file__))
SAMPLE_DIR = os.path.join(HERE, "sample_input_files")


# UI
BUSY_CSS = """
#busy_status {
  position: fixed;
  right: 1rem;
  top: 0.6rem;
  z-index: 1080;
  display: flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.4rem 0.75rem;
  border-radius: 0.5rem;
  background: var(--bs-body-bg, #fff);
  border: 1px solid var(--bs-border-color, #dee2e6);
  box-shadow: 0 0.25rem 0.75rem rgba(0, 0, 0, 0.12);
  opacity: 0;
  pointer-events: none;
  transition: opacity 0.1s linear 0s;      /* hides immediately when done */
}
html.shiny-busy #busy_status {
  opacity: 1;
  transition: opacity 0.1s linear 0.35s;   /* appears only if work is slow */
}
"""

app_ui = ui.page_sidebar(
    ui.sidebar(
        ui.input_file(
            "file", "Choose input file",
            accept=[".txt", ".csv", ".tsv"], multiple=False,
            placeholder="No file selected",
        ),
        ui.div(
            ui.download_link("download_samples", "Sample input files"),
            ui.tags.a(
                "Documentation on GitHub ↗",
                href="https://github.com/alingwist/maxentlab",
                target="_blank", rel="noopener",
            ),
            class_="d-flex flex-column gap-1",
        ),
        ui.hr(),
        ui.input_radio_buttons(
            "prior", "Prior",
            {"L2": "L2 (Gaussian)", "L1": "L1", "none": "None"},
            selected="L2",
        ),
        ui.panel_conditional(
            "input.prior === 'L2'",
            ui.input_numeric("sigma", "σ (higher = weaker prior)",
                             value=1000.0, min=0.0001, step=0.1),
        ),
        ui.panel_conditional(
            "input.prior === 'L1'",
            ui.input_numeric("alpha", "α (higher = stronger prior)",
                             value=0.01, min=0.0, step=0.01),
        ),
        ui.input_checkbox("allow_negative", "Allow negative weights", value=False),
        ui.input_action_button("generate", "Generate grammar", class_="btn-primary"),
        ui.output_ui("download_ui"),
        width=300,
    ),

    # bslib's main container is display:block, so its gap does not separate the
    # status card from the grid below; this class supplies the same spacing as
    # a margin, matching the gap between the two cards.
    ui.div(ui.output_ui("status"), class_="bslib-mb-spacing"),

    ui.layout_columns(
        ui.card(
            ui.card_header("Constraint weights"),
            ui.markdown(
                "Double-click a weight to set it manually — the tableau "
                "is regenerated by clicking Enter."
            ),
            ui.output_data_frame("weights_table"),
            ui.div(
                ui.input_action_button("reset_weights", "Reset",
                                       class_="btn-sm btn-outline-secondary"),
                class_="pt-2",
            ),
            full_screen=True,
        ),
        ui.card(
            ui.card_header("Tableau"),
            ui.output_ui("filter_bar"),
            ui.output_data_frame("tableau"),
            full_screen=True,
        ),
        # Side by side on a wide screen; stacked once that squeezes the
        # weights column to the point of being unreadable.
        col_widths={"sm": 12, "md": 12, "lg": [4, 8]},
    ),

    # Outside the sidebar: a fixed element nested in it could be clipped or
    # dragged along by the sidebar's own transforms.
    ui.div(
        ui.tags.span(class_="spinner-border spinner-border-sm",
                     aria_hidden="true"),
        "Computing…",
        id="busy_status", role="status", aria_live="polite",
        class_="text-muted small",
    ),

    ui.head_content(ui.tags.style(BUSY_CSS)),
    # Spinners over any output that is recomputing (the tableau after a weight
    # change), plus a progress bar across the top of the page.
    ui.busy_indicators.use(spinners=True, pulse=True),

    title="MaxEntLab",
    fillable=False,
)


# Server

def server(input, output, session):
    data_store = reactive.value(None)     # canonical input DataFrame
    fit_store = reactive.value(None)      # dict returned by optimize_weights
    manual_weights = reactive.value(None)  # hand-edited weights, or None

    # Fit
    @reactive.effect
    @reactive.event(input.generate)
    def _generate():
        file_info = input.file()
        if not file_info:
            ui.notification_show("No file was uploaded. Please upload a file.",
                                 type="error", duration=8)
            return

        path = file_info[0]["datapath"]
        name = file_info[0]["name"]
        if not name.lower().endswith((".txt", ".csv", ".tsv")):
            ui.notification_show(
                "The uploaded file is not a .txt or .csv file.",
                type="error", duration=8)
            return

        try:
            sep = "," if name.lower().endswith(".csv") else "\t"
            raw = pd.read_csv(path, sep=sep, encoding="utf-8")
            data = prepare_dataframe(raw)
        except Exception as exc:  # bad headers, bad encoding, ragged rows
            ui.notification_show(f"Could not read the file: {exc}",
                                 type="error", duration=12)
            return

        prior = input.prior()
        try:
            result = optimize_weights(
                data,
                reg=None if prior == "none" else prior,
                sigma=float(input.sigma() or 1000.0),
                alpha=float(input.alpha() or 0.0),
                lower_bound=None if input.allow_negative() else 0.0,
                verbose=False,
            )
        except Exception as exc:
            ui.notification_show(f"Could not fit the grammar: {exc}",
                                 type="error", duration=12)
            return

        data_store.set(data)
        fit_store.set(result)
        manual_weights.set(None)

    # Hand-edited weights
    def _weights_now():
        """Current weight vector, read outside of any reactive dependency."""
        with reactive.isolate():
            fit = fit_store.get()
            if fit is None:
                return None
            manual = manual_weights.get()
            return np.asarray(fit["weights"] if manual is None else manual,
                              dtype=float).copy()

    @reactive.effect
    @reactive.event(input.reset_weights)
    def _reset_weights():
        manual_weights.set(None)

    @reactive.calc
    def current_weights():
        fit = fit_store.get()
        if fit is None:
            return None
        manual = manual_weights.get()
        return fit["weights"] if manual is None else manual

    @reactive.calc
    def predictions():
        fit = fit_store.get()
        data = data_store.get()
        weights = current_weights()
        if fit is None or data is None:
            return None

        preds = predict_probabilities(data, weights, fit["constraint_names"])
        mae, per_tableau = compute_errors(preds)
        preds["MAE_per_tableau"] = [round(per_tableau[i], 6)
                                    for i in preds["Input"]]
        preds["MAE_overall"] = round(mae, 6)
        return preds

    # Search and filter
    def _input_value(name, default=""):
        """Read an input that may not exist yet (the filter bar is dynamic)."""
        try:
            value = input[name]()
        except Exception:
            return default
        return default if value is None else value

    @reactive.effect
    @reactive.event(input.clear_filters)
    def _clear_filters():
        ui.update_text("search", value="")
        ui.update_text("filter_value", value="")

    @reactive.calc
    def filtered_predictions():
        """Predictions narrowed by the search box and the column condition."""
        preds = predictions()
        if preds is None:
            return None
        rows = preds

        term = str(_input_value("search", "")).strip().lower()
        if term:
            labels = [c for c in ("Input", "Output", "Hidden") if c in rows.columns]
            if labels:
                keep = np.zeros(len(rows), dtype=bool)
                for col in labels:
                    keep |= (rows[col].astype(str).str.lower()
                             .str.contains(term, regex=False).to_numpy())
                rows = rows[keep]

        column = str(_input_value("filter_column", ""))
        operator = str(_input_value("filter_op", "contains"))
        value = str(_input_value("filter_value", "")).strip()
        if column in rows.columns and value:
            series = rows[column]
            numeric = pd.api.types.is_numeric_dtype(series)
            try:
                number = float(value)
            except ValueError:
                number = None

            if operator == "contains":
                rows = rows[series.astype(str).str.lower()
                            .str.contains(value.lower(), regex=False)]
            elif operator in ("eq", "ne"):
                if numeric and number is not None:
                    match = np.isclose(series.astype(float), number)
                else:
                    match = (series.astype(str).str.lower() == value.lower()).to_numpy()
                rows = rows[match if operator == "eq" else ~match]
            elif numeric and number is not None:
                rows = rows[{
                    "gt": series > number,
                    "ge": series >= number,
                    "lt": series < number,
                    "le": series <= number,
                }[operator]]
            # A numeric comparison against a text column, or a value that is not
            # a number, filters nothing rather than erroring.

        return rows

    @reactive.calc
    def tableau_frame():
        """Predictions with the grammar on top: one weight under each
        constraint column, blank under every other column.

        Display only — the downloaded file gets its own weights row from
        format_output, so this one is not written out twice. The weights row is
        added after filtering, so it is always present.
        """
        preds = filtered_predictions()
        fit = fit_store.get()
        if preds is None or fit is None:
            return None

        display = preds.copy()
        # Violations are read as integers; the weights row puts floats in the
        # same columns, so widen them first rather than truncating the weights.
        for name in fit["constraint_names"]:
            display[name] = display[name].astype(float)

        weights = dict(zip(fit["constraint_names"],
                           np.round(np.asarray(current_weights(), dtype=float), 4)))
        row = {}
        for col in display.columns:
            if col in weights:
                row[col] = float(weights[col])
            elif pd.api.types.is_numeric_dtype(display[col]):
                row[col] = np.nan          # renders blank
            else:
                row[col] = "weights" if col == display.columns[0] else ""

        weight_row = pd.DataFrame([row])[display.columns]
        return pd.concat([weight_row, display], ignore_index=True)

    # Status
    @render.ui
    def status():
        fit = fit_store.get()
        data = data_store.get()
        if fit is None or data is None:
            return ui.card(ui.markdown(
                "Upload a tab-separated tableau file and click "
                "**Generate grammar**.\n\n"
                "Columns: `input`, `output`, an optional `hidden` column for "
                "hidden structure, `probability` (probabilities, percentages "
                "or raw counts — always normalized within a tableau), then "
                "one column per constraint."
            ))

        preds = predictions()
        mae, _ = compute_errors(preds)
        hidden = has_hidden_structure(data)
        edited = manual_weights.get() is not None

        bits = [
            f"**{data['Input'].nunique()}** tableaux",
            f"**{len(fit['constraint_names'])}** constraints",
            ("hidden structure: **yes** (predictions are summed over parses)"
             if hidden else "hidden structure: **no**"),
            f"log-likelihood **{fit['loglik']:.4f}**",
            f"mean absolute error **{mae:.5f}**",
        ]
        if not fit["converged"]:
            bits.append(f"⚠ optimizer: {fit['message']}")
        if edited:
            bits.append("✎ showing hand-edited weights")

        return ui.card(ui.markdown(" &nbsp;|&nbsp; ".join(bits)))

    # Tables
    @render.data_frame
    def weights_table():
        fit = fit_store.get()
        weights = current_weights()
        if fit is None:
            return render.DataGrid(pd.DataFrame({"Constraint": [], "Weight": []}))
        df = pd.DataFrame({
            "Constraint": fit["constraint_names"],
            "Weight": np.round(np.asarray(weights, dtype=float), 4),
        })
        return render.DataGrid(df, editable=True, height="420px", width="100%")

    @weights_table.set_patch_fn
    def _patch_weight(*, patch, **_kwargs):
        """Apply one hand-edited weight as soon as the cell is committed."""
        weights = _weights_now()
        row = patch["row_index"]
        if weights is None or not (0 <= row < len(weights)):
            return patch["value"]
        try:
            value = float(str(patch["value"]).strip())
        except (TypeError, ValueError):
            ui.notification_show(f"'{patch['value']}' is not a number.",
                                 type="error", duration=6)
            return f"{weights[row]:g}"       # revert the cell
        weights[row] = value
        manual_weights.set(weights)
        return f"{value:g}"

    @render.ui
    def filter_bar():
        # Depends on the fit alone, so typing in the boxes never rebuilds (and
        # so never blurs) the bar. The column list is read without taking a
        # dependency on the predictions themselves.
        fit = fit_store.get()
        if fit is None:
            return ui.div()
        with reactive.isolate():
            preds = predictions()
        columns = list(preds.columns) if preds is not None else []

        def field(width, *children):
            return ui.div(*children, class_="mb-0", style=f"width:{width};")

        return ui.div(
            field("15rem",
                  ui.input_text("search", None,
                                placeholder="Search inputs and outputs…")),
            field("11rem",
                  ui.input_select("filter_column", None,
                                  choices=["(no filter)"] + columns,
                                  selected="(no filter)")),
            field("7.5rem",
                  ui.input_select("filter_op", None, choices={
                      "contains": "contains",
                      "eq": "=", "ne": "≠",
                      "gt": ">", "ge": "≥",
                      "lt": "<", "le": "≤",
                  }, selected="contains")),
            field("7rem", ui.input_text("filter_value", None, placeholder="value")),
            ui.input_action_button("clear_filters", "Clear",
                                   class_="btn-sm btn-outline-secondary"),
            ui.div(ui.output_text("row_count"), class_="text-muted small ms-auto"),
            class_="d-flex flex-wrap gap-2 align-items-center pb-2",
        )

    @render.text
    def row_count():
        preds = predictions()
        shown = filtered_predictions()
        if preds is None or shown is None:
            return ""
        if len(shown) == len(preds):
            return f"{len(preds)} rows"
        return f"{len(shown)} of {len(preds)} rows"

    @render.data_frame
    def tableau():
        frame = tableau_frame()
        if frame is None:
            return render.DataGrid(pd.DataFrame())
        # No column filters: their input boxes sit directly under the headers,
        # where they read as editable cells rather than as filters.
        # summary off: the filter bar reports the row count itself, without
        # counting the weights row as data.
        return render.DataGrid(frame, height="420px", width="100%",
                               filters=False, summary=False)

    # Downloads
    @render.ui
    def download_ui():
        if fit_store.get() is None:
            return ui.div()
        return ui.download_button("download_output", "Download output",
                                  class_="btn-outline-primary mt-2")

    @render.download_button(filename="output-tableau.txt")
    def download_output():
        preds = predictions()
        fit = fit_store.get()
        if preds is None or fit is None:
            return
        yield format_output(preds, current_weights(), fit["constraint_names"])

    @render.download_link(filename="sample_input_files.zip")
    def download_samples():
        buffer = io.BytesIO()
        with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as zf:
            if os.path.isdir(SAMPLE_DIR):
                for fname in sorted(os.listdir(SAMPLE_DIR)):
                    fpath = os.path.join(SAMPLE_DIR, fname)
                    if os.path.isfile(fpath):
                        zf.write(fpath, arcname=fname)
        yield buffer.getvalue()


app = App(app_ui, server)
